apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-gokul-infra-dev

resources:
  - ../../base
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  environment: dev

images:
  - name: PLACEHOLDER_ECR_URI
    newName: PLACEHOLDER_ECR_URI
    newTag: latest
