apiVersion: v1
kind: Service
metadata:
  name: gokul-infra
  namespace: opsera-gokul-infra-dev
  labels:
    app: gokul-infra
    tenant: opsera
    environment: dev
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: gokul-infra
  sessionAffinity: None
