apiVersion: v1
kind: ConfigMap
metadata:
  name: gokul-s-delight-ui-config
  namespace: opsera-gokul-s-delight-ui-dev
  labels:
    app: gokul-s-delight-ui
    tenant: opsera
data:
  ENVIRONMENT: "dev"
  PORT: "8080"
  NODE_ENV: "production"
