apiVersion: v1
kind: ServiceAccount
metadata:
  name: gokul-s-delight-ui
  namespace: opsera-gokul-s-delight-ui-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::792373136340:role/gokul-s-delight-ui-irsa-role
  labels:
    app: gokul-s-delight-ui
    tenant: opsera
