apiVersion: v1
kind: ConfigMap
metadata:
  name: gokul-hello-config
  namespace: opsera-gokul-hello-dev
  labels:
    app: gokul-hello
    tenant: opsera
data:
  ENVIRONMENT: "dev"
  NODE_ENV: "production"
