apiVersion: v1
kind: Service
metadata:
  name: gokul-hello
  namespace: opsera-gokul-hello-dev
  labels:
    app: gokul-hello
    tenant: opsera
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: gokul-hello
