apiVersion: v1
kind: ServiceAccount
metadata:
  name: gokul-hello
  namespace: opsera-gokul-hello-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::PLACEHOLDER_AWS_ACCOUNT_ID:role/opsera-gokul-hello-irsa
  labels:
    app: gokul-hello
    tenant: opsera
