apiVersion: v1
kind: ServiceAccount
metadata:
  name: gokul-infra
  namespace: opsera-gokul-infra-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::PLACEHOLDER_AWS_ACCOUNT_ID:role/gokul-infra-irsa-role
  labels:
    app: gokul-infra
    tenant: opsera
imagePullSecrets:
  - name: ecr-registry-secret
