apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-gokul-s-delight-ui-dev

resources:
- ../../base

labels:
- pairs:
    environment: dev
    deployment-strategy: rolling
  includeSelectors: false

images:
- name: PLACEHOLDER_ECR_URI
  newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/gokul-s-delight-ui
  newTag: 9d02371-20260217-104441
