apiVersion: v1
kind: Service
metadata:
  name: gokul-demo
  namespace: opsera-gokul-demo-dev
  labels:
    app: gokul-demo
    tenant: opsera
spec:
  type: ClusterIP
  selector:
    app: gokul-demo
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
