apiVersion: apps/v1
kind: Deployment
metadata:
  name: gokul-demo
spec:
  template:
    spec:
      containers:
      - name: gokul-demo
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: NODE_ENV
          value: "production"
