apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gokul-demo
  namespace: opsera-gokul-demo-dev
  labels:
    app: gokul-demo
    tenant: opsera
    environment: dev
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - gokul-demo-dev.agent.opsera.dev
    secretName: gokul-demo-dev-tls
  rules:
  - host: gokul-demo-dev.agent.opsera.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gokul-demo
            port:
              number: 80
