apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-gokul-demo-dev

resources:
  - ../../base
  - ingress.yaml

replicas:
  - name: gokul-demo
    count: 2

commonLabels:
  environment: dev

patchesStrategicMerge:
  - deployment-patch.yaml
