apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gokul-hello
  namespace: opsera-gokul-hello-dev
  labels:
    app: gokul-hello
    tenant: opsera
spec:
  ingressClassName: nginx
  rules:
  - host: gokul-hello-dev.agent.opsera.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gokul-hello
            port:
              number: 80
