apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-gokul-hello-dev

resources:
  - ../../base

images:
  - name: PLACEHOLDER_ECR_URI
    newName: PLACEHOLDER_ECR_URI
    newTag: latest

commonLabels:
  environment: dev

replicas:
  - name: gokul-hello
    count: 2
